name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: src/go.mod
      - name: Run tests
        working-directory: src
        run: go test ./...

  goreleaser:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: src/go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.3
        with:
          distribution: goreleaser
          version: v2.18.2
          args: release --clean --config ../.goreleaser.yml
          workdir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: binaries
          path: src/dist/*